Add error message for  cloning sdk timeout (#395)
Issue [#1642](https://github.com/aws-controllers-k8s/community/issues/1642):

Description of changes:
add message to remind user to clone aws-go-sdk when timeout due to bad network speed 

```shell
// original
➜  code-generator git:(main) make build-controller SERVICE=ecr
building ack-generate ... ok.
==== building ecr-controller ====
Copying common custom resource definitions into ecr
Building Kubernetes API objects for ecr
Error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1

// with new error message
➜  code-generator git:(main) ✗ make build-controller SERVICE=ecr
building ack-generate ... ok.
==== building ecr-controller ====
Copying common custom resource definitions into ecr
Building Kubernetes API objects for ecr
Error: cannot clone repository: take too long to clone sdk repo, please consider run 'git clone https://github.com/aws/aws-sdk-go' into cache dir /Users/julian/.cache/aws-controllers-k8s/src/aws-sdk-go
make: *** [build-controller] Error 1

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.