fix ack-generate release
When running `./test/release/test-helm.sh` from the community
repository, I was getting errors like this:

```
[jaypipes@thelio community]$ ./test/release/test-helm.sh s3 v0.0.2-37-g6c6957d-dirty
testing Helm release for s3 for release version v0.0.2-37-g6c6957d-dirty.
Building release artifacts for s3-v0.0.2-37-g6c6957d-dirty
Error: open apis: no such file or directory
```

The above was due to the `ack-generate release` command calling the
`getLatestAPIVersion()` function which in turn attempted to read the
(old, pre-split-repo) `services/$SERVICE/apis/` directory. We don't
actually need the latest API version when generating release artifacts
for a controller, but the `pkg/generate.New()` function requires an
APIVersion argument, so I'm just passing an empty string here, which
solves the above problem and allows the helm test to complete.