Default priorityClassName to blank string (#253)
Issue #, if available:
Relates https://github.com/aws-controllers-k8s/code-generator/pull/249
Relates https://github.com/aws-controllers-k8s/code-generator/pull/252

Description of changes:
This fixes a bug I introduced in a previous PR (sorry!)
This must default to an empty string rather than null or you get:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
s3-chart:
- deployment.priorityClassName: Invalid type. Expected: string, given: null

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.